spring:
#  datasource:
#    driver-class-name: dm.jdbc.driver.DmDriver
#    url: jdbc:dm://47.115.201.125:5236?schema=PRODUCTION
#    username: SYSDBA
#    password: SYSDBA001
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://#:3306/db_project
    username: root
    password: #
  mail:
    host: smtp.163.com
    username: #
    password:
    properties:
      from: qxd
  data:
    redis:
      database: 0
      host: #
      port: 6379
      password: