
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.218.160:3306/db_project?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Cqzod@123
  mail:
    host: smtp.163.com
    username: 18947336207@163.com
    password: HXRUEYCKHFHAMUGD
    port: 465
    properties:
      from: 18947336207@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host:
      port: